apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-versions
  namespace: fleet-default
spec:
  options:
    URI: "https://source.cloud.google.com/cpas-269913/cpas/main/upgrade/versions.json"
    Timeout: "1m"
  type: json